### ISSUE TITLE
Missing ruby multi_xml

### ISSUE THREAD

**Issue by alk-automize** [QuaeNocentDocent/omskemp#7]
Used the kemp-install.sh script and configured kemp.conf. When restarting the oms agent I get the following.

> May 24 11:58:39  omsagent[9411]: /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- multi_xml (LoadError)
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/plugin/kemp_lib.rb:5:in `<module:KempRest>'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/plugin/kemp_lib.rb:1:in `<top (required)>'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:89:in `block in load_plugin_dir'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:87:in `each'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/plugin.rb:87:in `load_plugin_dir'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/engine.rb:138:in `load_plugin_dir'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:513:in `block in init_engine'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:510:in `each'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:510:in `init_engine'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:166:in `block in start'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:360:in `main_process'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/supervisor.rb:164:in `start'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.3.0/gems/fluentd-0.12.24/bin/fluentd:5:in `<top (required)>'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/bin/omsagent:22:in `load'
May 24 11:58:39  omsagent[9411]:         from /opt/microsoft/omsagent/bin/omsagent:22:in `<main>'

OS: Ubuntu 16.04 lts
OMS agent: 1.3.4-15

**Comment by alk-automize** [comment]
Fixed it with the following command.

` sudo /opt/microsoft/omsagent/ruby/bin/gem install multi_xml`

Maybe it should be included in kemp-install.sh
